version: '3'

services:
 db:
  image: mysql:5.7
  command: mysqld --default-authentication-plugin=mysql_native_password
  volumes:
   - db_data:/var/lib/mysql
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: toor
   MYSQL_DATABASE: ped
   MYSQL_USER: magalu
   MYSQL_PASSWORD: M4g4lu
  ports:
   - "3333:3306"

 web:
  build: .
  command: python3 manage.py runserver 0.0.0.0:8000
  volumes:
   - .:/app
  ports:
   - "8000:8000"
  depends_on:
   - db
    
volumes:
 db_data:
